"""User adding column moderator.

Revision ID: 42b6b70cb979
Revises: 0d7073f62a5d
Create Date: 2022-02-23 11:46:11.275806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42b6b70cb979'
down_revision = '0d7073f62a5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('moderator', sa.Boolean(), nullable=False, default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'moderator')
    # ### end Alembic commands ###
