"""empty message

Revision ID: 508fd5b4f3ef
Revises: af2f993ec830
Create Date: 2022-02-25 14:35:19.255786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508fd5b4f3ef'
down_revision = 'af2f993ec830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pyramid', '_Pyramid__special_hashed_value_')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pyramid', sa.Column('_Pyramid__special_hashed_value_', sa.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
