"""empty message

Revision ID: 5aafacf31019
Revises: e1726d3825c6
Create Date: 2022-02-19 11:47:16.738679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aafacf31019'
down_revision = 'e1726d3825c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variable_model')
    op.add_column('formula', sa.Column('isMain', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formula', 'isMain')
    op.create_table('variable_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('variable_name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('formula_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['formula_id'], ['formula.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variable_name')
    )
    # ### end Alembic commands ###
