"""empty message

Revision ID: 5d1aeb4c8147
Revises: 01df64f86631
Create Date: 2022-02-25 14:56:48.086388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d1aeb4c8147'
down_revision = '01df64f86631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pyramid', '_Pyramid__special_hashed_value_')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pyramid', sa.Column('_Pyramid__special_hashed_value_', sa.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
