"""empty message

Revision ID: 5d7d7b788c99
Revises: 7a8cd11a4ae2
Create Date: 2022-02-25 14:06:39.571514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d7d7b788c99'
down_revision = '7a8cd11a4ae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pyramid', sa.Column('_Pyramid__special_hashed_value_', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pyramid', '_Pyramid__special_hashed_value_')
    # ### end Alembic commands ###
