"""empty message

Revision ID: 7a8cd11a4ae2
Revises: a4a9f4b83e1d
Create Date: 2022-02-25 14:05:46.037051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a8cd11a4ae2'
down_revision = 'a4a9f4b83e1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pyramid', sa.Column('_Pyramid__special_hashed_value_', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pyramid', '_Pyramid__special_hashed_value_')
    # ### end Alembic commands ###
