"""empty message

Revision ID: 93795a85a3e6
Revises: 5aafacf31019
Create Date: 2022-02-20 19:16:34.861461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93795a85a3e6'
down_revision = '5aafacf31019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('formula', 'pyramid_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('formula', 'pyramid_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
