"""User adding column moderator.

Revision ID: a4a9f4b83e1d
Revises: 42b6b70cb979
Create Date: 2022-02-23 11:50:23.929506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4a9f4b83e1d'
down_revision = '42b6b70cb979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('moderator', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'moderator')
    # ### end Alembic commands ###
