"""empty message

Revision ID: ab7587ad2d61
Revises: 5d1aeb4c8147
Create Date: 2022-02-25 14:57:12.651524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab7587ad2d61'
down_revision = '5d1aeb4c8147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pyramid', '_Pyramid__special_hashed_value_')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pyramid', sa.Column('_Pyramid__special_hashed_value_', sa.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
