"""empty message

Revision ID: c85c19f24d66
Revises: 93795a85a3e6
Create Date: 2022-02-20 19:20:25.033645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c85c19f24d66'
down_revision = '93795a85a3e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('formula', 'pyramid_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('formula', 'pyramid_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
