"""User, Pyramid tables

Revision ID: e1726d3825c6
Revises: 
Create Date: 2022-02-17 19:52:56.747513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1726d3825c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('profile_imagefile', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('pyramid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('generating_function', sa.String(length=140), nullable=False),
    sa.Column('explicit_formula', sa.String(length=140), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('explicit_formula'),
    sa.UniqueConstraint('generating_function'),
    sa.UniqueConstraint('sequence_number')
    )
    op.create_table('relations',
    sa.Column('linked_pyramid_id', sa.Integer(), nullable=True),
    sa.Column('relatedto_pyramid_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['linked_pyramid_id'], ['pyramid.id'], ),
    sa.ForeignKeyConstraint(['relatedto_pyramid_id'], ['pyramid.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relations')
    op.drop_table('pyramid')
    op.drop_table('user')
    # ### end Alembic commands ###
